---
# tasks file for github-runner

- name: Get ansible facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Include setup systemd tasks
  ansible.builtin.include_tasks:
    file: systemd.yml
